apiVersion: v1
kind: Namespace
metadata:
  name: ilo
  labels:
    app: ilo

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ilo
  namespace: ilo
spec:
  selector:
    matchLabels:
      app: ilo
  template:
    metadata:
      labels:
        app: ilo
    spec:
      containers:
      - name: ilo
        image: 525158249545.dkr.ecr.us-west-2.amazonaws.com/ilo:v14
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8443

---

apiVersion: v1
kind: Service
metadata:
  name: ilo
  namespace: ilo
spec:
  selector:
    app: ilo
  ports:
  - port: 8443
    targetPort: 8443


