apiVersion: ilo.prabhatsharma.in/v1alpha1
kind: AdmissionPolicy
metadata:
  name: crappypolicy1
  namespace: default
spec:
  rules:
  - name: rule1
    resource: pod
    validationFailureAction: enforce
    rule: resource['metadata']['name'] == 'crappy'


